import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import "./../_assets/css/main.css";
import Sidebar from '../_components/Sidebar/Sidebar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
      </head>
      <body className={`is-preload ${inter.className}`}>
        <div id="wrapper">
          <div id="main">
            {children}
          </div>
          <div id="sidebar">
            <Sidebar />
            <a href="#sidebar" className="toggle">Toggle</a>
          </div>
        </div>
      </body>
    </html>
  )
}
